package irac

import (
	"testing"
	"time"
)

func TestProvenance_IsValid(t *testing.T) {
	now := time.Now().UTC()
	tests := []struct {
		name string
		p    Provenance
		want bool
	}{
		{"valid", Provenance{GeneratedBy: "extractor", GeneratedAt: now}, true},
		{"empty generated by", Provenance{GeneratedBy: "", GeneratedAt: now}, false},
		{"zero generated at", Provenance{GeneratedBy: "extractor"}, false},
		{"empty", Provenance{}, false},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := tt.p.IsValid(); got != tt.want {
				t.Errorf("IsValid() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestValidConfidence(t *testing.T) {
	tests := []struct {
		name string
		c    float64
		want bool
	}{
		{"zero", 0, true},
		{"one", 1, true},
		{"mid", 0.5, true},
		{"negative", -0.01, false},
		{"above one", 1.01, false},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := ValidConfidence(tt.c); got != tt.want {
				t.Errorf("ValidConfidence(%v) = %v, want %v", tt.c, got, tt.want)
			}
		})
	}
}

func TestProvenance_UpstreamNodeIDs(t *testing.T) {
	p := Provenance{
		GeneratedBy:     "application-engine",
		GeneratedAt:     time.Now().UTC(),
		UpstreamNodeIDs: []string{"f1", "r1"},
	}
	if len(p.UpstreamNodeIDs) != 2 {
		t.Fatalf("UpstreamNodeIDs len = %d, want 2", len(p.UpstreamNodeIDs))
	}
	if p.UpstreamNodeIDs[0] != "f1" || p.UpstreamNodeIDs[1] != "r1" {
		t.Errorf("UpstreamNodeIDs = %v, want [f1 r1]", p.UpstreamNodeIDs)
	}
}
