import clsx from 'clsx';
import { XIcon } from 'lucide-react';
import { Button } from '@/components/ui/Button';
import type { TreeNode } from '@/types';
import {
  NODE_TYPE_COLORS,
  NODE_TYPE_LABELS,
  confidenceTier,
  formatConfidence,
} from '@/lib/treeLayout';

export interface TreeNodeDetailProps {
  node: TreeNode;
  onClose: () => void;
  className?: string;
}

const CONFIDENCE_BAR_CLASSES: Record<ReturnType<typeof confidenceTier>, string> = {
  low: 'bg-red-400',
  medium: 'bg-amber-400',
  high: 'bg-emerald-500',
};

/**
 * Detail side panel shown when a reasoning-tree node is selected. Surfaces
 * the node's full text, its source span(s)/citation back to the ingested
 * document, its confidence score, and (for RuleNode/ConclusionNode) the
 * jurisdiction tag and non-binding guardrail label.
 */
export function TreeNodeDetail({ node, onClose, className }: TreeNodeDetailProps) {
  const colors = NODE_TYPE_COLORS[node.type];
  const tier = confidenceTier(node.confidence);

  return (
    <div
      data-testid="tree-node-detail"
      className={clsx(
        'flex flex-col gap-4 rounded-lg border border-neutral-200 bg-white p-4 dark:border-neutral-700 dark:bg-neutral-800',
        className,
      )}
    >
      <div className="flex items-start justify-between gap-2">
        <span
          className="inline-flex items-center rounded-full px-2.5 py-1 text-xs font-semibold"
          style={{ backgroundColor: colors.fill, color: colors.text }}
        >
          {NODE_TYPE_LABELS[node.type]}
        </span>
        <button
          type="button"
          aria-label="Close node detail"
          onClick={onClose}
          className="rounded-md p-1 text-neutral-400 hover:bg-neutral-100 hover:text-neutral-600 dark:hover:bg-neutral-700"
        >
          <XIcon className="h-4 w-4" aria-hidden="true" />
        </button>
      </div>

      <p className="text-sm text-neutral-800 dark:text-neutral-100">{node.text}</p>

      {node.label && (
        <p className="rounded-md bg-amber-50 px-3 py-2 text-xs font-medium text-amber-800 dark:bg-amber-900/30 dark:text-amber-200">
          Guardrail label: {node.label}
        </p>
      )}

      {(node.jurisdictionCode || node.legalFamily) && (
        <div className="text-xs text-neutral-500 dark:text-neutral-400">
          {node.jurisdictionCode && <p>Jurisdiction: {node.jurisdictionCode}</p>}
          {node.legalFamily && <p>Legal family: {node.legalFamily}</p>}
        </div>
      )}

      <div>
        <div className="mb-1 flex items-center justify-between text-xs font-medium text-neutral-500 dark:text-neutral-400">
          <span>Confidence</span>
          <span data-testid="tree-node-detail-confidence">{formatConfidence(node.confidence)}</span>
        </div>
        <div className="h-1.5 w-full overflow-hidden rounded-full bg-neutral-200 dark:bg-neutral-700">
          <div
            className={clsx('h-full rounded-full', CONFIDENCE_BAR_CLASSES[tier])}
            style={{ width: formatConfidence(node.confidence) }}
          />
        </div>
      </div>

      <div>
        <p className="mb-1 text-xs font-medium text-neutral-500 dark:text-neutral-400">
          Source span &amp; citation
        </p>
        {node.spans && node.spans.length > 0 ? (
          <ul className="space-y-1.5" data-testid="tree-node-detail-spans">
            {node.spans.map((span, index) => (
              <li
                key={index}
                className="rounded-md border border-neutral-200 px-2.5 py-1.5 text-xs text-neutral-600 dark:border-neutral-700 dark:text-neutral-300"
              >
                Offset [{span.start}–{span.end}]
                {typeof span.page === 'number' && span.page > 0 && <span> · Page {span.page}</span>}
                {typeof span.startMs === 'number' && span.startMs > 0 && (
                  <span>
                    {' '}
                    · {(span.startMs / 1000).toFixed(1)}s–{((span.endMs ?? span.startMs) / 1000).toFixed(1)}s
                  </span>
                )}
              </li>
            ))}
          </ul>
        ) : (
          <p className="text-xs text-neutral-400">No source span recorded for this node.</p>
        )}
      </div>

      {node.provenance && (
        <div className="text-xs text-neutral-400">
          <p>Generated by {node.provenance.generatedBy || 'unknown'}</p>
          {node.provenance.upstreamNodeIds && node.provenance.upstreamNodeIds.length > 0 && (
            <p>Derived from {node.provenance.upstreamNodeIds.length} upstream node(s)</p>
          )}
        </div>
      )}

      <Button variant="ghost" size="sm" onClick={onClose} className="self-start">
        Close
      </Button>
    </div>
  );
}
