DROP FUNCTION IF EXISTS verdex_set_app_role_password(text);

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM verdex_app;

REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM verdex_app;
REVOKE USAGE ON SCHEMA public FROM verdex_app;

DROP ROLE IF EXISTS verdex_app;
