DROP POLICY IF EXISTS tenant_isolation ON case_transitions;
ALTER TABLE case_transitions NO FORCE ROW LEVEL SECURITY;
ALTER TABLE case_transitions DISABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation ON cases;
ALTER TABLE cases NO FORCE ROW LEVEL SECURITY;
ALTER TABLE cases DISABLE ROW LEVEL SECURITY;
