package caselifecycle

import (
	"context"

	"github.com/google/uuid"
)

// CaseFilter narrows a List call. Zero-value fields are treated as
// "no filter on this field".
type CaseFilter struct {
	// State, if non-empty, restricts results to cases in this State.
	State State

	// JurisdictionID, if non-nil, restricts results to cases under
	// this jurisdiction.
	JurisdictionID uuid.UUID

	// CategoryID, if non-empty, restricts results to cases with this
	// CategoryID.
	CategoryID string
}

// Repository persists Case records and their TransitionRecord audit
// log, scoped to a tenant on every call. Implementations must refuse
// (via ErrCrossTenantAccess) to operate on a Case whose TenantID does
// not match the tenantID argument, before touching storage.
//
// Two implementations are provided: PostgresRepository (backed by the
// `cases` and `case_transitions` tables — see
// packages/persistence/migrations/000006_create_cases.up.sql) and
// InMemoryRepository (for tests and other packages' fixtures).
type Repository interface {
	// Create inserts c. c.ID is generated by NewCase; Create returns
	// ErrInvalidCase if c fails Validate, and ErrCrossTenantAccess if
	// c.TenantID does not match tenantID.
	Create(ctx context.Context, tenantID uuid.UUID, c *Case) error

	// Get returns the case with the given id, scoped to tenantID. It
	// returns ErrNotFound if no such case is visible to tenantID
	// (either because it does not exist, or because it belongs to a
	// different tenant).
	Get(ctx context.Context, tenantID, id uuid.UUID) (*Case, error)

	// List returns every case visible to tenantID matching filter.
	List(ctx context.Context, tenantID uuid.UUID, filter CaseFilter) ([]*Case, error)

	// Update overwrites the mutable fields of c (title, reference,
	// category, state, metadata, metadata version, archived-at) for
	// the case identified by c.ID, scoped to tenantID. It returns
	// ErrNotFound if no such case is visible to tenantID, and
	// ErrCrossTenantAccess if c.TenantID does not match tenantID.
	Update(ctx context.Context, tenantID uuid.UUID, c *Case) error

	// AppendTransition persists r as part of the case's transition
	// audit log. Implementations should treat this as append-only:
	// transition records are never updated or deleted.
	AppendTransition(ctx context.Context, tenantID uuid.UUID, r *TransitionRecord) error

	// ListTransitions returns every TransitionRecord for caseID,
	// scoped to tenantID, ordered by OccurredAt ascending (oldest
	// first).
	ListTransitions(ctx context.Context, tenantID, caseID uuid.UUID) ([]*TransitionRecord, error)
}
